openapi: '3.0.2'
info:
  title: Hooks Publisher API
  version: '1.0'
servers:
  - url: https://api-dev.apigee-x.theapishop.com
paths:
  /hooks/{topic}/subs:
    post:
      parameters:
        - name: topic
          in: path
          description: The topic to subscribe to.
          required: true
          example: suppliers
          schema:
            type: string
            enum:
              - suppliers
              - orders
              - customers
      requestBody:
        description: The hooks push configuraiton
        content:
          application/json:
            schema:
              type: object
              properties:
                pushConfig:
                  type: object
                  properties:
                    pushEndpoint:
                      type: string
                      description: The endpoint to receive the POST events at
                      example: https://webhook-client-h7pi7igbcq-ew.a.run.app/webhook
                    oidcToken:
                      type: object
                      properties:
                        servicAccountEmail:
                          type: string
                          description: The service account to use for an OIDC token for authentication
                          example: service@project.iam.gserviceaccount.com
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        data:
                          type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  fault:
                    type: object
                    properties:
                      faultString:
                        type: string
                        description: The type of fault and further information on reason.
                        example: 
                      detail:
                        type: object
                        properties:
                          errorcode:
                            type: string
                            description: Exact error code
                            example: steps.oauth.v2.FailedToResolveAPIKey
                        